# Generated by Django 4.0.3 on 2022-04-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskuser', '0003_profile_address_line1_profile_city_profile_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
